version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_GOOGLE_CLIENT_ID=${REACT_APP_GOOGLE_CLIENT_ID}
      - REACT_APP_PROD=${REACT_APP_PROD}
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - CLIENT=${CLIENT}
      - SESSION_SECRET=${SESSION_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_TO=${SMTP_TO}
      - TODOIST_CLIENT_ID=${TODOIST_CLIENT_ID}
      - TODOIST_CLIENT_SECRET=${TODOIST_CLIENT_SECRET}
      - TODOIST_REDIRECT_URL=${TODOIST_REDIRECT_URL}
      - TICKTICK_CLIENT_ID=${TICKTICK_CLIENT_ID}
      - TICKTICK_CLIENT_SECRET=${TICKTICK_CLIENT_SECRET}
      - TICKTICK_REDIRECT_URL=${TICKTICK_REDIRECT_URL}

      